### ISSUE TITLE
No output from CLI with no arguments is confusing

### ISSUE THREAD

**Issue by 1j01** [tractordev/apptron#51]
I suggest reserving no arguments `$ apptron` for showing help.

The first thing people are likely to do after installing a command-line program is to run it with no arguments (if they don't feel like trying `--help` first since often it isn't necessary.)
If they see no output, they will likely assume the installation is broken, or that the program doesn't work on their computer.
I think it would be a lot friendlier to people exploring the functions of the program, if you can always return to `$ apptron` to see what the features are.

As I understand it, the qtalk stdio protocol is for programmatic usage only, and so a command won't need to be typed out repeatedly, so it should be fine if it's a little longer, like `apptron qtalk` or `apptron stdio` or `apptron api`\* or even `apptron -` as some programs use `-` to refer to stdio usage — though I think being explicit and more visible would be better. (\*"api" seems ambiguous, since the whole CLI is an API.)
This also makes it less special, so you can use `apptron [command] -help` for more information about the STDIO API service. (Otherwise, how would you access this help?)

I thought this would be a good thing to bring up in beta, although IIRC you already mentioned the no arguments behavior in a demo video, and I hate the idea of invalidating that and you probably do too, haha...
(As an alternative, would it be possible for the qtalk stdio protocol include a short help message when starting up?)

**Comment by progrium** [comment]
Finally got this into main: dab2fd3cb76b5d64b59d1d336caffff2abd6a78b

Thanks for making a point about it!
