### ISSUE TITLE
add battery API

### ISSUE THREAD

**Issue by holic** [tractordev/apptron#52]
I have a tiny little app/tool I've been wanting to build for a while now and a great excuse to play with Apptron.

I often ignore my battery indicator when it gets to 5-10% (in the flow or whatever), but then forget and suddenly my laptop dies, which is even more disruptive of an interruption. I'd like to make an app that yells at me louder and louder as the battery approaches 2% and 1%, maybe slowly fading the screen to red/black.

Would be great to have some battery APIs for this!

**Comment by nickav** [comment]
Is there anything else the API should support in addition to percentage? Maybe knowing whether or not the device is charging.
Another thing that might be nice is the ability to prevent the computer from sleeping

It looks like battery percentage on Windows is just this:
```cpp
int getBatteryLevel()
{
    SYSTEM_POWER_STATUS status;
    GetSystemPowerStatus(&status);
    return status.BatteryLifePercent;
}
```

**Comment by progrium** [comment]
I would have thought electron had more, but it seems the main thing they expose is whether you're on battery or not. So maybe:

* is on battery
* is charging
* battery %

**Comment by progrium** [comment]
#63 was merged, battery API added
